services:
  app:
    build:
      context: ./
      dockerfile: backend/Dockerfiles/app/Dockerfile
    ports:
      - "22217:3000"
    volumes:
      - .:/backend
    restart: always
    depends_on:
      - database

  database:
    build:
      context: ./
      dockerfile: backend/Dockerfiles/database/Dockerfile
    ports:
      - "5069:3306"
    environment:
      MYSQL_DATABASE: games_db
      MYSQL_USER: dandelionWriter
      MYSQL_PASSWORD: 0908072244!
      MYSQL_ROOT_PASSWORD: 0908072244X!
    volumes:
      - ./backend/mysql-data:/var/lib/mysql